### ISSUE TITLE
Contact us content update

### ISSUE THREAD

**Issue by pavani0116** [kloudlite/kloudlite#271]
We need to assure user that we won't spam in privacy section

**Comment by pavani0116** [comment]
Thanks for reaching out!
We’ve got your message and are on it. Stay tuned for our reply!

Cheers,
Team Kloudlite

**Comment by karthik1729** [comment]
@shweta-kaushal

**Comment by karthik1729** [comment]
We need to show near terms and conditions that we are not going to spam you.

**Comment by karthik1729** [comment]
@pavani0116

**Comment by pavani0116** [comment]
done.
