### ISSUE TITLE
[BUG] DNS issues on alpine based containers

### ISSUE THREAD

**Issue by nxtcoder17** [kloudlite/kloudlite#304]
Aparrently, search parameters in `/etc/resolv.conf` in alpine does not work as intended, and cause any query to `getaddrinfo` syscall with `domainName` + first item in search params

References:
- https://github.com/nodejs/docker-node/issues/602

**Comment by abdheshnayak** [comment]
![Screenshot From 2024-11-10 23-29-18](https://github.com/user-attachments/assets/583631cd-294f-45b3-b6e5-7445822c69b4)
![Screenshot From 2024-11-10 23-12-04](https://github.com/user-attachments/assets/ce96894a-176a-41d8-91ca-87a0b9a59e95)
