### ISSUE TITLE
[KLO-86] Logo in email need to be updated

### ISSUE THREAD

**Issue by karthik1729** [kloudlite/kloudlite#37]
<sub>From [SyncLinear.com](https://synclinear.com) | [KLO-86](https://linear.app/kloudlite/issue/KLO-86/logo-in-email-need-to-be-updated)</sub>

**Comment by karthik1729** [comment]
![Group 81logo-full.png](https://uploads.linear.app/8cd455bc-2b7b-4fdf-89d0-341a85149ec3/25c1e93b-1424-492f-9e6c-6b748828f0ed/130df6a1-bf1d-487f-bf80-0cc2d1e5c637?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzhjZDQ1NWJjLTJiN2ItNGZkZi04OWQwLTM0MWE4NTE0OWVjMy8yNWMxZTkzYi0xNDI0LTQ5MmYtOWU2Yy02Yjc0ODgyOGYwZWQvMTMwZGY2YTEtYmYxZC00ODdmLWJmODAtMGNjMmQxZTVjNjM3IiwiaWF0IjoxNzA4MTk2MDEyLCJleHAiOjE3MDgyODI0MTJ9.HUfxJgdko6Wa6AS5hAvldGKwb8mlVtDQpRs0qLE9qVs)

to be updated with this image

**Comment by nxtcoder17** [comment]
![Here it is](https://github.com/kloudlite/oss/assets/22402557/3120d517-9376-4ecb-be8f-fd8a85642394)

**Comment by nxtcoder17** [comment]
![kloudlite-logo](https://github.com/kloudlite/kloudlite/assets/22402557/f8ad384d-ebd1-489a-8c3f-09ce58b310ad)

**Comment by nxtcoder17** [comment]
![kloudlite logo](https://github.com/kloudlite/kloudlite/assets/22402557/dee0044b-9e1d-4247-9a71-dc520e6ad219)

**Comment by nxtcoder17** [comment]
this issue is coming again, this time we are managing all our static assets in [kloudlite/static-assets](https://github.com/kloudlite/static-assets), and kloudlite logo URL is from there only
